### ISSUE TITLE
profiles.json points to nonexistent downloads

### ISSUE THREAD

**Issue by eliminmax** [radareorg/r2env#32]
I was looking into the possibility of using the GitHub API to get the list of available versions in a private copy of this repo - if and when I figure that out, I'm hoping to open a pull request here.

As part of doing that, I was trying to figure out how to parse the GitHub API output and restructure it to fit within the structure of `profiles.json`. When comparing the results of my attempt with the actual `profiles.json` file, I noticed several inconsistencies between the files available in the GitHub releases and the files that `profiles.json` listed.

If you have access to the "requests" python library, you can run the following snippet to get a list of files in `profiles.json` that are not available to download, if you simply set the `PATH_TO_PROFILES_JSON` variable appropriately.

```python
import requests, json
PATH_TO_PROFILES_JSON = 'SET THIS VALUE'
with open(PATH_TO_PROFILES_JSON) as f:
    profiles = json.load(f)

api_resp=requests.get('https://api.github.com/repos/radareorg/radare2/releases', {'headers': ['X-GitHub-Api-Version: 2022-11-28', 'Accept: application/vnd.github+json']}).json()
available_files_per_version = {}
for version in api_resp:
    available_files_per_version[version['tag_name']] = [asset['name'] for asset in version['assets']]

for version in profiles['radare2']['versions']:
    for file in version['packages'].values():
        if file not in available_files_per_version[version['id']]:
            print(file)
```

That lists the following for me:
```
radare2-5.4.0-w64.zip
radare2-5.4.0.pkg
radare2-5.5.0-amd64.pkg
radare2-5.5.0-m1.pkg
radare2-5.5.2-amd64.pkg
radare2-5.5.2-m1.pkg
radare2-5.5.4-amd64.pkg
radare2-5.5.4-m1.pkg
radare2-5.6.0-amd64.pkg
radare2-5.6.0-m1.pkg
radare2-5.6.2-amd64.pkg
radare2-5.6.2-m1.pkg
radare2-5.6.4-amd64.pkg
radare2-5.6.4-m1.pkg
radare2-5.6.6-amd64.pkg
radare2-5.6.6-m1.pkg
radare2-5.6.8-amd64.pkg
radare2-5.6.8-m1.pkg
radare2-5.7.0-amd64.pkg
radare2-5.7.0-m1.pkg
radare2-5.7.2-amd64.pkg
radare2-5.7.2-m1.pkg
radare2-5.7.4-amd64.pkg
radare2-5.7.4-m1.pkg
radare2-5.7.6-amd64.pkg
radare2-5.7.6-m1.pkg
radare2-5.7.8-amd64.pkg
radare2-5.7.8-m1.pkg
radare2-5.8.0-amd64.pkg
radare2-5.8.0-m1.pkg
```

**Comment by trufae** [comment]
Can you send a PR with your suggestion? i also think it will be better if r2env doesnt uses profiles because this way we wont need to depend on releasing every now and then, and just pick the info from github release page

**Comment by eliminmax** [comment]
It's incomplete right now, but once it's ready, I'd be happy to.

**Comment by eliminmax** [comment]
Just noticed that this issue was left open, but my patch was merged early last month. I'm going to go ahead and close it.
